### ISSUE TITLE
@import rules are ignored

### ISSUE THREAD

**Issue by GitHub-Mike** [janreges/siteone-crawler#31]
CSS files in link tags are created locally, but CSS files contained within these files in @import rules are ignored.

```html
<link href="/plugins/system/pagebuilder/assets/css/jsn-gui-frontend.css" rel="stylesheet" type="text/css">
```

```css
/* jsn-gui-frontend.css */
@import url("../joomlashine/css/jsn-bootstrap.css");
@import url("../joomlashine/css/jsn-fonticomoon.css");
@import url("../3rd-party/font-icomoon/css/icomoon.css");
@import url("../3rd-party/font-awesome/css/font-awesome.min.css");
```

**Comment by janreges** [comment]
@GitHub-Mike - done in c964fea1382fec71b990ac2cd89683590694d5b3 - could you check with current version in `main` branch?

**Comment by GitHub-Mike** [comment]
There is a 2nd problem. In the file bootstrap.min.css changes seem to have been made after the download. Example:

```css
/* web version */
.navbar-light .navbar-toggler-icon {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(0, 0, 0, 0.5)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E")
}

.navbar-light .navbar-text {
    color: rgba(0,0,0,.5)
}
```

```css
/* local version */
.navbar-light .navbar-toggler-icon {
    background-image: url(_data_image/svg_xml;charset=utf8,_3Csvg_viewBox=_0_0_30_30_xmlns=_http_//www.w3.org/2000/svg_3E_3Cpath_stroke=_rgba(0,_0,_0,_0.html)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E")
}

.navbar-light .navbar-text{
	color:rgba(0,0,0,.5)
}
```

There is probably a problem with a regex, because " | ' | , have been replaced by _. Is this possibly related to the changes in #30?
